package GiaoDienLogin;

import static java.lang.System.exit;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRootPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author DELL
 */
public class GiaoDienBanHang extends javax.swing.JFrame {

    /**
     * 
     */
    public GiaoDienBanHang() {
        initComponents();
        this.setLocationRelativeTo(null);
        comboxKH.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NhapTTKH = new javax.swing.ButtonGroup();
        NhapTTSach = new javax.swing.ButtonGroup();
        Header = new javax.swing.JPanel();
        Maxsize = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        LeftSay = new javax.swing.JLabel();
        CenterSay = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LeftMenu = new javax.swing.JPanel();
        BanHang = new javax.swing.JLabel();
        NhapHang = new javax.swing.JLabel();
        TuSach = new javax.swing.JLabel();
        TaiKhoan = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        NhanVien = new javax.swing.JLabel();
        KhachHang = new javax.swing.JLabel();
        ThongKe = new javax.swing.JLabel();
        Middle = new javax.swing.JPanel();
        Search = new javax.swing.JButton();
        ThemBtn = new javax.swing.JButton();
        newHD = new javax.swing.JPanel();
        ttKH = new javax.swing.JLabel();
        maHD = new javax.swing.JLabel();
        NhaptenKH = new javax.swing.JTextField();
        ttNV = new javax.swing.JLabel();
        Chuacotaikhoan = new javax.swing.JRadioButton();
        Dacotaikhoan = new javax.swing.JRadioButton();
        maHDtext = new javax.swing.JTextField();
        comboxKH = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        SuaBtn = new javax.swing.JButton();
        XoaBtn = new javax.swing.JButton();
        Sachtable = new javax.swing.JScrollPane();
        dataSach = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1400, 800));

        Header.setBackground(new java.awt.Color(0, 51, 51));
        Header.setMaximumSize(new java.awt.Dimension(1400, 32));
        Header.setPreferredSize(new java.awt.Dimension(1400, 32));

        Maxsize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giaodienchuan/images/icons8-minimize-window-30.png"))); // NOI18N

        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giaodienchuan/images/icons8-close-window-30.png"))); // NOI18N
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });

        LeftSay.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        LeftSay.setForeground(new java.awt.Color(255, 255, 255));
        LeftSay.setText("Hello, User");

        CenterSay.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        CenterSay.setForeground(new java.awt.Color(204, 204, 255));
        CenterSay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CenterSay.setText("BÁN HÀNG");
        CenterSay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giaodienchuan/images/icons8_replay_30px.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(LeftSay, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(428, 428, 428)
                .addComponent(CenterSay)
                .addGap(603, 603, 603)
                .addComponent(Maxsize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Close)
                .addGap(18, 18, 18))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LeftSay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CenterSay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Maxsize)
                    .addComponent(Close))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        LeftMenu.setBackground(new java.awt.Color(0, 51, 51));
        LeftMenu.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        BanHang.setBackground(new java.awt.Color(0, 102, 0));
        BanHang.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        BanHang.setForeground(new java.awt.Color(204, 255, 204));
        BanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giaodienchuan/images/icons8_small_business_30px_3.png"))); // NOI18N
        BanHang.setText("Bán Hàng");
        BanHang.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 0)));
        BanHang.setIconTextGap(5);

        NhapHang.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        NhapHang.setForeground(new java.awt.Color(204, 255, 204));
        NhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giaodienchuan/images/icons8_downloads_30px.png"))); // NOI18N
        NhapHang.setText("Nhập Hàng");
        NhapHang.setIconTextGap(5);
        NhapHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NhapHangMouseClicked(evt);
            }
        });

        TuSach.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        TuSach.setForeground(new java.awt.Color(204, 255, 204));
        TuSach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giaodienchuan/images/icons8-bookcase-30.png"))); // NOI18N
        TuSach.setText("Kho Sách");
        TuSach.setIconTextGap(5);
        TuSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TuSachMouseClicked(evt);
            }
        });

        TaiKhoan.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        TaiKhoan.setForeground(new java.awt.Color(204, 255, 204));
        TaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giaodienchuan/images/icons8-account-30.png"))); // NOI18N
        TaiKhoan.setText("Tài Khoản");
        TaiKhoan.setIconTextGap(5);
        TaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TaiKhoanMouseClicked(evt);
            }
        });

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giaodienchuan/images/icons8_exit_30px.png"))); // NOI18N

        NhanVien.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        NhanVien.setForeground(new java.awt.Color(204, 255, 204));
        NhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giaodienchuan/images/icons8_assistant_30px.png"))); // NOI18N
        NhanVien.setText("Nhân Viên");
        NhanVien.setIconTextGap(5);
        NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NhanVienMouseClicked(evt);
            }
        });

        KhachHang.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        KhachHang.setForeground(new java.awt.Color(204, 255, 204));
        KhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giaodienchuan/images/icons8_user_30px.png"))); // NOI18N
        KhachHang.setText("Khách Hàng");
        KhachHang.setIconTextGap(5);
        KhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KhachHangMouseClicked(evt);
            }
        });

        ThongKe.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        ThongKe.setForeground(new java.awt.Color(204, 255, 204));
        ThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giaodienchuan/images/icons8_bar_chart_30px.png"))); // NOI18N
        ThongKe.setText("Thống Kê");
        ThongKe.setMaximumSize(new java.awt.Dimension(121, 32));
        ThongKe.setMinimumSize(new java.awt.Dimension(121, 32));
        ThongKe.setPreferredSize(new java.awt.Dimension(121, 32));
        ThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThongKeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout LeftMenuLayout = new javax.swing.GroupLayout(LeftMenu);
        LeftMenu.setLayout(LeftMenuLayout);
        LeftMenuLayout.setHorizontalGroup(
            LeftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LeftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(LeftMenuLayout.createSequentialGroup()
                        .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 89, Short.MAX_VALUE))
                    .addComponent(NhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TuSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(KhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ThongKe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        LeftMenuLayout.setVerticalGroup(
            LeftMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftMenuLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(BanHang)
                .addGap(30, 30, 30)
                .addComponent(NhapHang)
                .addGap(30, 30, 30)
                .addComponent(TuSach)
                .addGap(30, 30, 30)
                .addComponent(TaiKhoan)
                .addGap(30, 30, 30)
                .addComponent(NhanVien)
                .addGap(30, 30, 30)
                .addComponent(KhachHang)
                .addGap(30, 30, 30)
                .addComponent(ThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 659, Short.MAX_VALUE)
                .addComponent(Logout)
                .addContainerGap())
        );

        getContentPane().add(LeftMenu, java.awt.BorderLayout.LINE_START);

        Middle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));
        Middle.setToolTipText("");
        Middle.setAutoscrolls(true);
        Middle.setMaximumSize(new java.awt.Dimension(980, 800));
        Middle.setOpaque(false);
        Middle.setPreferredSize(new java.awt.Dimension(980, 600));

        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giaodienchuan/images/icons8-magnifying-glass-30.png"))); // NOI18N
        Search.setToolTipText("Tìm kiếm");
        Search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Search.setBorderPainted(false);
        Search.setContentAreaFilled(false);
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        ThemBtn.setBackground(new java.awt.Color(204, 255, 204));
        ThemBtn.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        ThemBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giaodienchuan/images/icons8_add_30px.png"))); // NOI18N
        ThemBtn.setText("Thêm");
        ThemBtn.setToolTipText("Thêm mới hóa đơn bán hàng");
        ThemBtn.setHideActionText(true);
        ThemBtn.setMaximumSize(new java.awt.Dimension(130, 37));
        ThemBtn.setMinimumSize(new java.awt.Dimension(130, 37));
        ThemBtn.setPreferredSize(new java.awt.Dimension(130, 37));
        ThemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemBtnActionPerformed(evt);
            }
        });

        newHD.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Bán Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 12))); // NOI18N

        ttKH.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        ttKH.setText("Khách Hàng Mua");

        maHD.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        maHD.setText("Mã Hóa Đơn");

        NhaptenKH.setText("Nhập tên Khách Hàng");
        NhaptenKH.setEnabled(false);
        NhaptenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhaptenKHActionPerformed(evt);
            }
        });

        ttNV.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        ttNV.setText("Nhân Viên");

        NhapTTKH.add(Chuacotaikhoan);
        Chuacotaikhoan.setText("Chưa có tài khoản");
        Chuacotaikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChuacotaikhoanActionPerformed(evt);
            }
        });

        NhapTTKH.add(Dacotaikhoan);
        Dacotaikhoan.setText("Đã có tài khoản");
        Dacotaikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DacotaikhoanActionPerformed(evt);
            }
        });

        maHDtext.setText("HD01");
        maHDtext.setEnabled(false);
        maHDtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maHDtextActionPerformed(evt);
            }
        });

        comboxKH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khách hàng 1", "Khách hàng 2", "Khách hàng 3", "Khách hàng4", " " }));
        comboxKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxKHActionPerformed(evt);
            }
        });

        jTextField2.setText("User");
        jTextField2.setEnabled(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setText("Thêm Mới Khách Hàng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newHDLayout = new javax.swing.GroupLayout(newHD);
        newHD.setLayout(newHDLayout);
        newHDLayout.setHorizontalGroup(
            newHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newHDLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(newHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(newHDLayout.createSequentialGroup()
                        .addGroup(newHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Dacotaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ttKH, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Chuacotaikhoan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(newHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NhaptenKH)
                            .addComponent(comboxKH, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(newHDLayout.createSequentialGroup()
                        .addGroup(newHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ttNV, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maHD, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(newHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2)
                            .addComponent(maHDtext))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        newHDLayout.setVerticalGroup(
            newHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newHDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maHD)
                    .addComponent(maHDtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ttNV)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ttKH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dacotaikhoan)
                    .addComponent(comboxKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Chuacotaikhoan)
                    .addComponent(NhaptenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(188, Short.MAX_VALUE))
        );

        SuaBtn.setBackground(new java.awt.Color(204, 255, 204));
        SuaBtn.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        SuaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giaodienchuan/images/icons8_wrench_30px.png"))); // NOI18N
        SuaBtn.setText("Sửa");
        SuaBtn.setToolTipText("Sửa hóa đơn nhập sai");
        SuaBtn.setMaximumSize(new java.awt.Dimension(130, 37));
        SuaBtn.setMinimumSize(new java.awt.Dimension(130, 37));
        SuaBtn.setPreferredSize(new java.awt.Dimension(130, 37));
        SuaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaBtnActionPerformed(evt);
            }
        });

        XoaBtn.setBackground(new java.awt.Color(204, 255, 204));
        XoaBtn.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        XoaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giaodienchuan/images/icons8_cancel_30px_1.png"))); // NOI18N
        XoaBtn.setText("Xóa");
        XoaBtn.setToolTipText("Xóa hóa đơn bị lỗi");
        XoaBtn.setMaximumSize(new java.awt.Dimension(130, 37));
        XoaBtn.setMinimumSize(new java.awt.Dimension(130, 37));
        XoaBtn.setPreferredSize(new java.awt.Dimension(130, 37));
        XoaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaBtnActionPerformed(evt);
            }
        });

        Sachtable.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 12))); // NOI18N

        dataSach.setAutoCreateRowSorter(true);
        dataSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"HD1", "NV1", "KH1", "KM1", "20-03-2024",  new Long(30000)},
                {"HD2", "NV2", "KH2", "KM1", "30-03-2023",  new Long(40000)},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Hóa Đơn", "Mã Nhân Viên", "Mã Khách", "Mã Khuyến Mãi", "Ngày lập", "Tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataSach.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        dataSach.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        dataSach.setShowGrid(true);
        dataSach.setSurrendersFocusOnKeystroke(true);
        dataSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataSachMouseClicked(evt);
            }
        });
        Sachtable.setViewportView(dataSach);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Sản Phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 12))); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Sách", "Tên Sách", "Số Lượng Còn Lại", "Đơn giá", "Nhà Xuất Bản"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Long.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setEnabled(false);
        jTable2.setShowGrid(true);
        jScrollPane1.setViewportView(jTable2);

        jTextField1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jTextField1.setActionCommand("k");
        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 12))); // NOI18N
        jTextField1.setFocusable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giaodienchuan/images/icons8_refresh_30px.png"))); // NOI18N
        jButton2.setText("Làm mới");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi Tiết Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 12))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1400, 32));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Hóa Đơn", "Mã Sách", "Tên Sách", "Số Lượng ", "Đơn Giá", "Thành Tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Long.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setShowGrid(true);
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout MiddleLayout = new javax.swing.GroupLayout(Middle);
        Middle.setLayout(MiddleLayout);
        MiddleLayout.setHorizontalGroup(
            MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiddleLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MiddleLayout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Search)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(MiddleLayout.createSequentialGroup()
                        .addGroup(MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(MiddleLayout.createSequentialGroup()
                                .addComponent(Sachtable, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MiddleLayout.createSequentialGroup()
                                .addComponent(ThemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SuaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(XoaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MiddleLayout.setVerticalGroup(
            MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiddleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search))
                .addGap(7, 7, 7)
                .addGroup(MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                    .addComponent(Sachtable, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ThemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SuaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(XoaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(290, 290, 290))
        );

        getContentPane().add(Middle, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        // TODO add your handling code here:
        exit(0);
    }//GEN-LAST:event_CloseMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void dataSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataSachMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dataSachMouseClicked

    private void XoaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XoaBtnActionPerformed

    private void SuaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SuaBtnActionPerformed

    private void comboxKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboxKHActionPerformed

    private void maHDtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maHDtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maHDtextActionPerformed

    private void DacotaikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DacotaikhoanActionPerformed
        // TODO add your handling code here:
        if(Dacotaikhoan.isSelected()){
            comboxKH.setEnabled(true);
            NhaptenKH.setEnabled(false);
            NhaptenKH.setText("Nhập tên Khách Hàng");
        }
    }//GEN-LAST:event_DacotaikhoanActionPerformed

    private void ChuacotaikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChuacotaikhoanActionPerformed
        // TODO add your handling code here:
        if(Chuacotaikhoan.isSelected()){
            comboxKH.setEnabled(false);
            NhaptenKH.setEnabled(true);
            NhaptenKH.setText("");

        }
    }//GEN-LAST:event_ChuacotaikhoanActionPerformed

    private void NhaptenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhaptenKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NhaptenKHActionPerformed

    private void ThemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ThemBtnActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void NhapHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhapHangMouseClicked
        // TODO add your handling code here:
        GiaoDienNhapHang nh=new GiaoDienNhapHang();
        nh.setVisible(true);
    }//GEN-LAST:event_NhapHangMouseClicked

    private void TuSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TuSachMouseClicked
        // TODO add your handling code here:
        GiaoDienKhoSach ts=new GiaoDienKhoSach();
        ts.setVisible(true);
    }//GEN-LAST:event_TuSachMouseClicked

    private void TaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TaiKhoanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TaiKhoanMouseClicked

    private void NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhanVienMouseClicked
        // TODO add your handling code here:
        GiaoDienNhanVien nv=new GiaoDienNhanVien();
        nv.setVisible(true);
    }//GEN-LAST:event_NhanVienMouseClicked

    private void KhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KhachHangMouseClicked
        // TODO add your handling code here:
        GiaoDienKhachHang kh=new GiaoDienKhachHang();
        kh.setVisible(true);
    }//GEN-LAST:event_KhachHangMouseClicked

    private void ThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThongKeMouseClicked
        // TODO add your handling code here:
        GiaoDienThongKe tk=new GiaoDienThongKe();
        tk.setVisible(true);
    }//GEN-LAST:event_ThongKeMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        GiaoDienChuan m=new GiaoDienChuan();
        m.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienBanHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BanHang;
    private javax.swing.JLabel CenterSay;
    private javax.swing.JRadioButton Chuacotaikhoan;
    private javax.swing.JLabel Close;
    private javax.swing.JRadioButton Dacotaikhoan;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel KhachHang;
    private javax.swing.JPanel LeftMenu;
    private javax.swing.JLabel LeftSay;
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel Maxsize;
    private javax.swing.JPanel Middle;
    private javax.swing.JLabel NhanVien;
    private javax.swing.JLabel NhapHang;
    private javax.swing.ButtonGroup NhapTTKH;
    private javax.swing.ButtonGroup NhapTTSach;
    private javax.swing.JTextField NhaptenKH;
    private javax.swing.JScrollPane Sachtable;
    private javax.swing.JButton Search;
    private javax.swing.JButton SuaBtn;
    private javax.swing.JLabel TaiKhoan;
    private javax.swing.JButton ThemBtn;
    private javax.swing.JLabel ThongKe;
    private javax.swing.JLabel TuSach;
    private javax.swing.JButton XoaBtn;
    private javax.swing.JComboBox<String> comboxKH;
    private javax.swing.JTable dataSach;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel maHD;
    private javax.swing.JTextField maHDtext;
    private javax.swing.JPanel newHD;
    private javax.swing.JLabel ttKH;
    private javax.swing.JLabel ttNV;
    // End of variables declaration//GEN-END:variables
}
