/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Main;
/**
 *
 * @author xuand
 */
public class ThongKePanel extends javax.swing.JPanel {

    /**
     * Creates new form ThongKePanel
     */
    public ThongKePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ThongKeCuaHang = new javax.swing.JTabbedPane();
        SUM = new javax.swing.JPanel();
        BanRa = new javax.swing.JScrollPane();
        DataBanRa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        TongHoaDon = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TenKhachHang = new javax.swing.JTextField();
        TinhTongToanBoHoaDon = new javax.swing.JButton();
        TongToanBoHoaDon = new javax.swing.JTextField();
        MAX = new javax.swing.JPanel();
        HoaDonLonNhat = new javax.swing.JScrollPane();
        DataHoaDonLonNhat = new javax.swing.JTable();
        NgayLapMax = new javax.swing.JPanel();
        NhapNgay1 = new javax.swing.JPanel();
        ChonNgay1 = new javax.swing.JButton();
        NhapNgay2 = new javax.swing.JPanel();
        ChonNgay2 = new javax.swing.JButton();
        TimHoaDonLonNhat = new javax.swing.JButton();
        AVG = new javax.swing.JPanel();
        TrungBinh = new javax.swing.JScrollPane();
        DataTrungBinh = new javax.swing.JTable();
        NgayLapTrungBinh = new javax.swing.JPanel();
        NhapNgay1TB = new javax.swing.JPanel();
        ChonNgay1TB = new javax.swing.JButton();
        NhapNgay2TB = new javax.swing.JPanel();
        ChonNgay2TB = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        KetQuaTB = new javax.swing.JTextField();
        TinhTrungBinh = new javax.swing.JButton();

        ThongKeCuaHang.setBorder(javax.swing.BorderFactory.createTitledBorder("Thống Kê Cửa Hàng"));

        DataBanRa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tên nhân viên", "Tên khách hàng", "Đơn giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DataBanRa.setShowGrid(true);
        BanRa.setViewportView(DataBanRa);

        jLabel1.setText("Tổng hóa đơn");

        TongHoaDon.setEnabled(false);

        jLabel2.setText("Tên khách hàng");

        TenKhachHang.setEnabled(false);
        TenKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TenKhachHangActionPerformed(evt);
            }
        });

        TinhTongToanBoHoaDon.setText("Tổng toàn bộ hóa đơn");

        TongToanBoHoaDon.setEnabled(false);

        javax.swing.GroupLayout SUMLayout = new javax.swing.GroupLayout(SUM);
        SUM.setLayout(SUMLayout);
        SUMLayout.setHorizontalGroup(
            SUMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SUMLayout.createSequentialGroup()
                .addGroup(SUMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SUMLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BanRa, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SUMLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(SUMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SUMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TongHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(TinhTongToanBoHoaDon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TongToanBoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 621, Short.MAX_VALUE))
        );
        SUMLayout.setVerticalGroup(
            SUMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SUMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SUMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SUMLayout.createSequentialGroup()
                        .addGroup(SUMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TongHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SUMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SUMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TinhTongToanBoHoaDon)
                        .addComponent(TongToanBoHoaDon)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BanRa, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(401, Short.MAX_VALUE))
        );

        ThongKeCuaHang.addTab("Tổng giá trị bán ra", SUM);

        DataHoaDonLonNhat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Hóa đơn", "Tên nhân viên", "Tên khách hàng", "Tên sản phẩm", "Số lượng", "Đơn giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DataHoaDonLonNhat.setShowGrid(true);
        HoaDonLonNhat.setViewportView(DataHoaDonLonNhat);

        NgayLapMax.setBorder(javax.swing.BorderFactory.createTitledBorder("Ngày lập"));

        NhapNgay1.setBackground(new java.awt.Color(255, 255, 255));
        NhapNgay1.setBorder(javax.swing.BorderFactory.createTitledBorder("Từ"));

        javax.swing.GroupLayout NhapNgay1Layout = new javax.swing.GroupLayout(NhapNgay1);
        NhapNgay1.setLayout(NhapNgay1Layout);
        NhapNgay1Layout.setHorizontalGroup(
            NhapNgay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );
        NhapNgay1Layout.setVerticalGroup(
            NhapNgay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        ChonNgay1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giaodienchuan/images/icons8_calendar_31_30px.png"))); // NOI18N
        ChonNgay1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChonNgay1ActionPerformed(evt);
            }
        });

        NhapNgay2.setBackground(new java.awt.Color(255, 255, 255));
        NhapNgay2.setBorder(javax.swing.BorderFactory.createTitledBorder("Đến"));

        javax.swing.GroupLayout NhapNgay2Layout = new javax.swing.GroupLayout(NhapNgay2);
        NhapNgay2.setLayout(NhapNgay2Layout);
        NhapNgay2Layout.setHorizontalGroup(
            NhapNgay2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );
        NhapNgay2Layout.setVerticalGroup(
            NhapNgay2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        ChonNgay2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giaodienchuan/images/icons8_calendar_31_30px.png"))); // NOI18N

        javax.swing.GroupLayout NgayLapMaxLayout = new javax.swing.GroupLayout(NgayLapMax);
        NgayLapMax.setLayout(NgayLapMaxLayout);
        NgayLapMaxLayout.setHorizontalGroup(
            NgayLapMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NgayLapMaxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NhapNgay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChonNgay1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NhapNgay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(ChonNgay2)
                .addContainerGap())
        );
        NgayLapMaxLayout.setVerticalGroup(
            NgayLapMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NgayLapMaxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NgayLapMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChonNgay1)
                    .addComponent(NhapNgay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NgayLapMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ChonNgay2)
                        .addComponent(NhapNgay2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TimHoaDonLonNhat.setText("Hóa đơn lớn nhất");
        TimHoaDonLonNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimHoaDonLonNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MAXLayout = new javax.swing.GroupLayout(MAX);
        MAX.setLayout(MAXLayout);
        MAXLayout.setHorizontalGroup(
            MAXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MAXLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MAXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MAXLayout.createSequentialGroup()
                        .addComponent(NgayLapMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(TimHoaDonLonNhat))
                    .addComponent(HoaDonLonNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 503, Short.MAX_VALUE))
        );
        MAXLayout.setVerticalGroup(
            MAXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MAXLayout.createSequentialGroup()
                .addGroup(MAXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NgayLapMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MAXLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(TimHoaDonLonNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HoaDonLonNhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(325, 325, 325))
        );

        ThongKeCuaHang.addTab("Hóa Đơn lớn nhất", MAX);

        DataTrungBinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên nhân viên", "Tên khách hàng", "Ngày lập", "Đơn giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DataTrungBinh.setShowGrid(true);
        TrungBinh.setViewportView(DataTrungBinh);

        NgayLapTrungBinh.setBorder(javax.swing.BorderFactory.createTitledBorder("Ngày lập"));

        NhapNgay1TB.setBackground(new java.awt.Color(255, 255, 255));
        NhapNgay1TB.setBorder(javax.swing.BorderFactory.createTitledBorder("Từ"));

        javax.swing.GroupLayout NhapNgay1TBLayout = new javax.swing.GroupLayout(NhapNgay1TB);
        NhapNgay1TB.setLayout(NhapNgay1TBLayout);
        NhapNgay1TBLayout.setHorizontalGroup(
            NhapNgay1TBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );
        NhapNgay1TBLayout.setVerticalGroup(
            NhapNgay1TBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        ChonNgay1TB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giaodienchuan/images/icons8_calendar_31_30px.png"))); // NOI18N
        ChonNgay1TB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChonNgay1TBActionPerformed(evt);
            }
        });

        NhapNgay2TB.setBackground(new java.awt.Color(255, 255, 255));
        NhapNgay2TB.setBorder(javax.swing.BorderFactory.createTitledBorder("Đến"));

        javax.swing.GroupLayout NhapNgay2TBLayout = new javax.swing.GroupLayout(NhapNgay2TB);
        NhapNgay2TB.setLayout(NhapNgay2TBLayout);
        NhapNgay2TBLayout.setHorizontalGroup(
            NhapNgay2TBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );
        NhapNgay2TBLayout.setVerticalGroup(
            NhapNgay2TBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        ChonNgay2TB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/giaodienchuan/images/icons8_calendar_31_30px.png"))); // NOI18N

        javax.swing.GroupLayout NgayLapTrungBinhLayout = new javax.swing.GroupLayout(NgayLapTrungBinh);
        NgayLapTrungBinh.setLayout(NgayLapTrungBinhLayout);
        NgayLapTrungBinhLayout.setHorizontalGroup(
            NgayLapTrungBinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NgayLapTrungBinhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NhapNgay1TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChonNgay1TB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NhapNgay2TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(ChonNgay2TB)
                .addContainerGap())
        );
        NgayLapTrungBinhLayout.setVerticalGroup(
            NgayLapTrungBinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NgayLapTrungBinhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NgayLapTrungBinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChonNgay1TB)
                    .addComponent(NhapNgay1TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NgayLapTrungBinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ChonNgay2TB)
                        .addComponent(NhapNgay2TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Trung bình ");

        KetQuaTB.setEnabled(false);
        KetQuaTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KetQuaTBActionPerformed(evt);
            }
        });

        TinhTrungBinh.setText("Tính trung bình tất cả");
        TinhTrungBinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TinhTrungBinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AVGLayout = new javax.swing.GroupLayout(AVG);
        AVG.setLayout(AVGLayout);
        AVGLayout.setHorizontalGroup(
            AVGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AVGLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AVGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AVGLayout.createSequentialGroup()
                        .addComponent(NgayLapTrungBinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(AVGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KetQuaTB, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(TinhTrungBinh))
                    .addComponent(TrungBinh, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(500, Short.MAX_VALUE))
        );
        AVGLayout.setVerticalGroup(
            AVGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AVGLayout.createSequentialGroup()
                .addGroup(AVGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AVGLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AVGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NgayLapTrungBinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AVGLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(KetQuaTB))))
                    .addGroup(AVGLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(TinhTrungBinh, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TrungBinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(319, Short.MAX_VALUE))
        );

        ThongKeCuaHang.addTab("Trung Bình", AVG);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ThongKeCuaHang, javax.swing.GroupLayout.DEFAULT_SIZE, 1238, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(ThongKeCuaHang, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TenKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TenKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TenKhachHangActionPerformed

    private void ChonNgay1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChonNgay1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChonNgay1ActionPerformed

    private void TimHoaDonLonNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimHoaDonLonNhatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimHoaDonLonNhatActionPerformed

    private void ChonNgay1TBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChonNgay1TBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChonNgay1TBActionPerformed

    private void KetQuaTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KetQuaTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KetQuaTBActionPerformed

    private void TinhTrungBinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TinhTrungBinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TinhTrungBinhActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AVG;
    private javax.swing.JScrollPane BanRa;
    private javax.swing.JButton ChonNgay1;
    private javax.swing.JButton ChonNgay1TB;
    private javax.swing.JButton ChonNgay2;
    private javax.swing.JButton ChonNgay2TB;
    private javax.swing.JTable DataBanRa;
    private javax.swing.JTable DataHoaDonLonNhat;
    private javax.swing.JTable DataTrungBinh;
    private javax.swing.JScrollPane HoaDonLonNhat;
    private javax.swing.JTextField KetQuaTB;
    private javax.swing.JPanel MAX;
    private javax.swing.JPanel NgayLapMax;
    private javax.swing.JPanel NgayLapTrungBinh;
    private javax.swing.JPanel NhapNgay1;
    private javax.swing.JPanel NhapNgay1TB;
    private javax.swing.JPanel NhapNgay2;
    private javax.swing.JPanel NhapNgay2TB;
    private javax.swing.JPanel SUM;
    private javax.swing.JTextField TenKhachHang;
    private javax.swing.JTabbedPane ThongKeCuaHang;
    private javax.swing.JButton TimHoaDonLonNhat;
    private javax.swing.JButton TinhTongToanBoHoaDon;
    private javax.swing.JButton TinhTrungBinh;
    private javax.swing.JTextField TongHoaDon;
    private javax.swing.JTextField TongToanBoHoaDon;
    private javax.swing.JScrollPane TrungBinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
