/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Gui.FormChinh;

import Bus.Impl.khachHangImpl;
import Dto.KHACHANG;
import Gui.FormAdd.AddKhachHang;
import Gui.FormEdit.EditKhachHang;
import java.awt.event.KeyEvent;



import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static org.apache.logging.log4j.util.Strings.isBlank;

/**
 *
 * @author xuand
 */
public class KhachHangPanel extends javax.swing.JPanel {

    /**
     * Creates new form KhachHangPanel
     */
    khachHangImpl khaHangImpl = new khachHangImpl();
    
    public KhachHangPanel() {
        initComponents();
    }
    public void loadKhachHangToTable() {
        DefaultTableModel model = (DefaultTableModel) KhachHangtb.getModel();
        model.setRowCount(0);

        try {
            System.out.print("hoạt động");
            ArrayList<KHACHANG> sachList = khaHangImpl.selectAll();

            for (KHACHANG khachang : sachList) {
                Object[] row = {khachang.getMakh(), khachang.getHoten(), khachang.getDiachi(), khachang.getDienthoai(), khachang.getEmail()};
                model.addRow(row);
            }
            String choose=(String) thuoctinh.getSelectedItem();
            inputSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, choose, javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 51, 51)));
  
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        XuatExcel = new javax.swing.JButton();
        dataKH = new javax.swing.JPanel();
        scroll1 = new javax.swing.JScrollPane();
        KhachHangtb = new javax.swing.JTable();
        Them = new javax.swing.JButton();
        Xoa = new javax.swing.JButton();
        Sua = new javax.swing.JButton();
        panelSearch = new javax.swing.JPanel();
        search = new javax.swing.JButton();
        thuoctinh = new javax.swing.JComboBox<>();
        inputSearch = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 153));
        setPreferredSize(new java.awt.Dimension(1250, 428));

        XuatExcel.setBackground(new java.awt.Color(204, 255, 204));
        XuatExcel.setForeground(new java.awt.Color(0, 51, 51));
        XuatExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_ms_excel_30px.png"))); // NOI18N
        XuatExcel.setText("Xuất Excel");
        XuatExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XuatExcelActionPerformed(evt);
            }
        });

        dataKH.setBackground(new java.awt.Color(0, 204, 204));

        scroll1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Khách Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 12), new java.awt.Color(0, 51, 51))); // NOI18N

        KhachHangtb.setAutoCreateRowSorter(true);
        KhachHangtb.setBackground(new java.awt.Color(204, 255, 204));
        KhachHangtb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        KhachHangtb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Địa chỉ", "Số Điện Thoại", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        KhachHangtb.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        KhachHangtb.setShowGrid(true);
        KhachHangtb.setSurrendersFocusOnKeystroke(true);
        scroll1.setViewportView(KhachHangtb);

        Them.setBackground(new java.awt.Color(204, 255, 204));
        Them.setForeground(new java.awt.Color(0, 51, 51));
        Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_add_30px.png"))); // NOI18N
        Them.setText("Thêm Khách Hàng");
        Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemActionPerformed(evt);
            }
        });

        Xoa.setBackground(new java.awt.Color(204, 255, 204));
        Xoa.setForeground(new java.awt.Color(0, 51, 51));
        Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_delete_30px_1.png"))); // NOI18N
        Xoa.setText("Xóa Khách Hàng");
        Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaActionPerformed(evt);
            }
        });

        Sua.setBackground(new java.awt.Color(204, 255, 204));
        Sua.setForeground(new java.awt.Color(0, 51, 51));
        Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_maintenance_30px.png"))); // NOI18N
        Sua.setText("Sửa Thông tin Khách Hàng");
        Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataKHLayout = new javax.swing.GroupLayout(dataKH);
        dataKH.setLayout(dataKHLayout);
        dataKHLayout.setHorizontalGroup(
            dataKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataKHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Them)
                .addGap(30, 30, 30)
                .addComponent(Xoa)
                .addGap(30, 30, 30)
                .addComponent(Sua)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataKHLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 1237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        dataKHLayout.setVerticalGroup(
            dataKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataKHLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sua)
                    .addComponent(Xoa)
                    .addComponent(Them))
                .addContainerGap())
        );

        panelSearch.setBackground(new java.awt.Color(0, 153, 153));
        panelSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 14), new java.awt.Color(204, 255, 204))); // NOI18N

        search.setBackground(new java.awt.Color(0, 204, 204));
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-magnifying-glass-30.png"))); // NOI18N
        search.setBorder(null);
        search.setContentAreaFilled(false);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        thuoctinh.setBackground(new java.awt.Color(204, 255, 204));
        thuoctinh.setForeground(new java.awt.Color(0, 51, 51));
        thuoctinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã Khách Hàng", "Tên Khách Hàng", "Địa Chỉ", "Số Điện Thoại", "Email" }));
        thuoctinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thuoctinhActionPerformed(evt);
            }
        });

        inputSearch.setBackground(new java.awt.Color(204, 255, 204));
        inputSearch.setForeground(new java.awt.Color(0, 51, 51));
        inputSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tất Cả", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 51, 51))); // NOI18N
        inputSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSearchActionPerformed(evt);
            }
        });
        inputSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputSearchKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout panelSearchLayout = new javax.swing.GroupLayout(panelSearch);
        panelSearch.setLayout(panelSearchLayout);
        panelSearchLayout.setHorizontalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(thuoctinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelSearchLayout.setVerticalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearchLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputSearch)
                    .addComponent(thuoctinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        inputSearch.getAccessibleContext().setAccessibleName("Mã Khác");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(XuatExcel))
                    .addComponent(dataKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(XuatExcel)))
                .addGap(18, 18, 18)
                .addComponent(dataKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void XuatExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XuatExcelActionPerformed
        // TODO add your handling code here:
        if(khaHangImpl.xuatExcel()==true){
            JOptionPane.showMessageDialog(this, "Xuất Thành Công", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "đã xảy ra lỗi", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_XuatExcelActionPerformed

    private void ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemActionPerformed
        // TODO add your handling code here:
        AddKhachHang x = new AddKhachHang();
        x.setVisible(true);
        x.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                loadKhachHangToTable();
            }
        });

    }//GEN-LAST:event_ThemActionPerformed

    private void XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaActionPerformed
        // TODO add your handling code here:
        int selectedRowIdx = KhachHangtb.getSelectedRow();
        if (selectedRowIdx != -1) { 
            Object value = KhachHangtb.getModel().getValueAt(selectedRowIdx, 0); 
            int intValue = Integer.parseInt(value.toString());
            KHACHANG khachang = new KHACHANG(intValue);
            khaHangImpl.xoaKhachHang(khachang);
            loadKhachHangToTable();
        }else{
            JOptionPane.showMessageDialog(this, "Vui Lòng Chọn tài khoản muốn xóa", "Lỗi", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_XoaActionPerformed

    private void SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaActionPerformed
        // TODO add your handling code here:
        int selectedRowIdx = KhachHangtb.getSelectedRow();
        if (selectedRowIdx != -1) { 
            EditKhachHang y = new EditKhachHang();
             y.setVisible(true);
            Object value = KhachHangtb.getModel().getValueAt(selectedRowIdx, 0); 
            Object tennv = KhachHangtb.getModel().getValueAt(selectedRowIdx, 1);
            Object dchi = KhachHangtb.getModel().getValueAt(selectedRowIdx, 2);
            Object sdt = KhachHangtb.getModel().getValueAt(selectedRowIdx, 3);
            Object email = KhachHangtb.getModel().getValueAt(selectedRowIdx, 4);
            
            y.addThongTin(value.toString(),tennv.toString(),dchi.toString(),sdt.toString(),email.toString());
            y.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                loadKhachHangToTable();
            }
        });
        }else{
            JOptionPane.showMessageDialog(this, "Vui Lòng Chọn tài khoản muốn Sửa", "Lỗi", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_SuaActionPerformed

    private void thuoctinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thuoctinhActionPerformed
        // TODO add your handling code here:
        String choose=(String) thuoctinh.getSelectedItem();
        inputSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, choose, javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 51, 51)));
        loadKhachHangToTable();
        inputSearch.setText("");
    }//GEN-LAST:event_thuoctinhActionPerformed

    private void inputSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSearchActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) KhachHangtb.getModel();
        model.setRowCount(0);
        
        String kieuTimKiem = (String) thuoctinh.getSelectedItem();
        String inputText = inputSearch.getText();
        if (isBlank(inputText)) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập từ khóa cần tìm", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ArrayList<KHACHANG> khList = khaHangImpl.timKiem(inputText,kieuTimKiem);
        for (KHACHANG khachHang : khList) {
            Object[] row = {khachHang.getMakh(), khachHang.getHoten(),khachHang.getDiachi(),khachHang.getDienthoai(),khachHang.getEmail()};
            model.addRow(row);
        }

    }//GEN-LAST:event_searchActionPerformed

    private void inputSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputSearchKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            search.doClick();
        }
    }//GEN-LAST:event_inputSearchKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable KhachHangtb;
    private javax.swing.JButton Sua;
    private javax.swing.JButton Them;
    private javax.swing.JButton Xoa;
    private javax.swing.JButton XuatExcel;
    private javax.swing.JPanel dataKH;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JScrollPane scroll1;
    private javax.swing.JButton search;
    private javax.swing.JComboBox<String> thuoctinh;
    // End of variables declaration//GEN-END:variables
}
