/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Gui.FormChinh;

import Bus.Impl.nhanVienImpl;
import Dto.NHANVIEN;
import Gui.FormAdd.AddNhanVien;
import Gui.FormEdit.EditNhanVien;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static org.apache.logging.log4j.util.Strings.isBlank;



/**
 *
 * @author xuand
 */
public class NhanVienPanel extends javax.swing.JPanel {

    nhanVienImpl nhanVienImpl1 = new nhanVienImpl();
    /**
     * Creates new form NhanVienPanel
     * 
     */
    public NhanVienPanel() {
        initComponents();
    }
    public void loadNhanVienToTable(){
        DefaultTableModel model = (DefaultTableModel) DataNhanVien.getModel();
        model.setRowCount(0);

        try {
            System.out.print("hoạt động");
            ArrayList<NHANVIEN> listNhanVien = nhanVienImpl1.getAllTaiKhoan();

            for (NHANVIEN nhanVien : listNhanVien) {
                Object[] row = {nhanVien.getManv(), nhanVien.getHoten(),nhanVien.getDiachi(),nhanVien.getEmail(),nhanVien.getDienthoai()};
                model.addRow(row);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelTimKiem = new javax.swing.JPanel();
        search = new javax.swing.JButton();
        thuoctinh = new javax.swing.JComboBox<>();
        inputsearch = new javax.swing.JTextField();
        XuatExcel = new javax.swing.JButton();
        dataNV = new javax.swing.JPanel();
        scroll1 = new javax.swing.JScrollPane();
        DataNhanVien = new javax.swing.JTable();
        Them = new javax.swing.JButton();
        Xoa = new javax.swing.JButton();
        Sua = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        PanelTimKiem.setBackground(new java.awt.Color(0, 153, 153));
        PanelTimKiem.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 14), new java.awt.Color(204, 255, 204))); // NOI18N

        search.setBackground(new java.awt.Color(0, 204, 204));
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-magnifying-glass-30.png"))); // NOI18N
        search.setBorder(null);
        search.setContentAreaFilled(false);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        thuoctinh.setBackground(new java.awt.Color(204, 255, 204));
        thuoctinh.setForeground(new java.awt.Color(0, 51, 51));
        thuoctinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã Nhân Viên", "Tên Nhân Viên", "Địa Chỉ", "Email", "Số Điện Thoại" }));
        thuoctinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thuoctinhActionPerformed(evt);
            }
        });

        inputsearch.setBackground(new java.awt.Color(204, 255, 204));
        inputsearch.setForeground(new java.awt.Color(0, 51, 51));
        inputsearch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mã Nhân Viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 51, 51))); // NOI18N
        inputsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputsearchKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout PanelTimKiemLayout = new javax.swing.GroupLayout(PanelTimKiem);
        PanelTimKiem.setLayout(PanelTimKiemLayout);
        PanelTimKiemLayout.setHorizontalGroup(
            PanelTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTimKiemLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(thuoctinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(inputsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelTimKiemLayout.setVerticalGroup(
            PanelTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTimKiemLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PanelTimKiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputsearch)
                    .addComponent(thuoctinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        XuatExcel.setBackground(new java.awt.Color(204, 255, 204));
        XuatExcel.setForeground(new java.awt.Color(0, 51, 51));
        XuatExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_ms_excel_30px.png"))); // NOI18N
        XuatExcel.setText("Xuất Excel");
        XuatExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XuatExcelActionPerformed(evt);
            }
        });

        dataNV.setBackground(new java.awt.Color(0, 204, 204));

        scroll1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Nhân Viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 14), new java.awt.Color(0, 51, 51))); // NOI18N

        DataNhanVien.setAutoCreateRowSorter(true);
        DataNhanVien.setBackground(new java.awt.Color(204, 255, 204));
        DataNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        DataNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Địa chỉ", "Email", "Số điện thoại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DataNhanVien.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        DataNhanVien.setShowGrid(false);
        DataNhanVien.setShowHorizontalLines(true);
        DataNhanVien.setShowVerticalLines(true);
        scroll1.setViewportView(DataNhanVien);

        javax.swing.GroupLayout dataNVLayout = new javax.swing.GroupLayout(dataNV);
        dataNV.setLayout(dataNVLayout);
        dataNVLayout.setHorizontalGroup(
            dataNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll1, javax.swing.GroupLayout.DEFAULT_SIZE, 1232, Short.MAX_VALUE)
                .addContainerGap())
        );
        dataNVLayout.setVerticalGroup(
            dataNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        Them.setBackground(new java.awt.Color(204, 255, 204));
        Them.setForeground(new java.awt.Color(0, 51, 51));
        Them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_add_30px.png"))); // NOI18N
        Them.setText("Thêm Nhân Viên");
        Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemActionPerformed(evt);
            }
        });

        Xoa.setBackground(new java.awt.Color(204, 255, 204));
        Xoa.setForeground(new java.awt.Color(0, 51, 51));
        Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_delete_30px_1.png"))); // NOI18N
        Xoa.setText("Xóa Nhân Viên");
        Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaActionPerformed(evt);
            }
        });

        Sua.setBackground(new java.awt.Color(204, 255, 204));
        Sua.setForeground(new java.awt.Color(0, 51, 51));
        Sua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_support_30px.png"))); // NOI18N
        Sua.setText("Sửa Nhân Viên");
        Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Them)
                        .addGap(30, 30, 30)
                        .addComponent(Sua)
                        .addGap(30, 30, 30)
                        .addComponent(Xoa)
                        .addGap(30, 30, 30)
                        .addComponent(XuatExcel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Xoa)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Them)
                                .addComponent(Sua)
                                .addComponent(XuatExcel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(dataNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void XuatExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XuatExcelActionPerformed
        // TODO add your handling code here:
        if(nhanVienImpl1.xuatExcel()==true){
            JOptionPane.showMessageDialog(this, "Xuất Thành Công", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "đã xảy ra lỗi", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_XuatExcelActionPerformed

    private void ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemActionPerformed
        // TODO add your handling code here:
        AddNhanVien x=new AddNhanVien();
        x.setVisible(true);
        x.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                loadNhanVienToTable();
            }
        });
    }//GEN-LAST:event_ThemActionPerformed

    private void XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaActionPerformed
        // TODO add your handling code here:\
       int selectedRowIdx = DataNhanVien.getSelectedRow();
        if (selectedRowIdx != -1) { 
            Object value = DataNhanVien.getModel().getValueAt(selectedRowIdx, 0); 
            int manv = Integer.parseInt(value.toString());
            NHANVIEN nhanvien = new NHANVIEN(manv);
            nhanVienImpl1.xoaNhanVien(nhanvien);
            loadNhanVienToTable();
        }else{
            JOptionPane.showMessageDialog(this, "Vui Lòng Chọn nhân viên muốn xóa", "Lỗi", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_XoaActionPerformed

    private void SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuaActionPerformed
        // TODO add your handling code here:
       
        int selectedRowIdx = DataNhanVien.getSelectedRow();
        if (selectedRowIdx != -1) {
            EditNhanVien y = new EditNhanVien();
            y.setVisible(true);
            Object manv = DataNhanVien.getModel().getValueAt(selectedRowIdx, 0);
            Object tennv = DataNhanVien.getModel().getValueAt(selectedRowIdx, 1);
            Object dchi = DataNhanVien.getModel().getValueAt(selectedRowIdx, 2);
            Object email = DataNhanVien.getModel().getValueAt(selectedRowIdx, 3);
            Object sdt = DataNhanVien.getModel().getValueAt(selectedRowIdx, 4);
            
            y.setData(manv.toString(),tennv.toString(),dchi.toString(),email.toString(),sdt.toString());
            y.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                    loadNhanVienToTable();
                }
            });
        }else{
            JOptionPane.showMessageDialog(this, "Vui Lòng Chọn tài khoản muốn Sửa", "Lỗi", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_SuaActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) DataNhanVien.getModel();
        model.setRowCount(0);

        String kieuTimKiem = (String) thuoctinh.getSelectedItem();
        String inputText = inputsearch.getText();
        if (isBlank(inputText)) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập từ khóa cần tìm", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ArrayList<NHANVIEN> nvList = nhanVienImpl1.timKiem(inputText,kieuTimKiem);
        for (NHANVIEN nhanVien : nvList) {
            Object[] row = {nhanVien.getManv(), nhanVien.getHoten(),nhanVien.getDiachi(),nhanVien.getEmail(),nhanVien.getDienthoai()};
            model.addRow(row);
        }
    }//GEN-LAST:event_searchActionPerformed

    private void inputsearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputsearchKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                    search.doClick();
                }
    }//GEN-LAST:event_inputsearchKeyPressed

    private void thuoctinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thuoctinhActionPerformed
        // TODO add your handling code here:
        String choose=(String) thuoctinh.getSelectedItem();
        inputsearch.setBorder(javax.swing.BorderFactory.createTitledBorder(null, choose, javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(0, 51, 51)));
        loadNhanVienToTable();
        inputsearch.setText("");
    }//GEN-LAST:event_thuoctinhActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DataNhanVien;
    private javax.swing.JPanel PanelTimKiem;
    private javax.swing.JButton Sua;
    private javax.swing.JButton Them;
    private javax.swing.JButton Xoa;
    private javax.swing.JButton XuatExcel;
    private javax.swing.JPanel dataNV;
    private javax.swing.JTextField inputsearch;
    private javax.swing.JScrollPane scroll1;
    private javax.swing.JButton search;
    private javax.swing.JComboBox<String> thuoctinh;
    // End of variables declaration//GEN-END:variables
}
