/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Gui.FormChinh;

import Bus.Impl.ThongKeImpl;
import Bus.Impl.khachHangImpl;
import Bus.Impl.nhanVienImpl;
//import Bus.Impl.HoaDonImpl;
import Dto.NHANVIEN;
import Dto.KHACHANG;
import Dto.HOADON;
import Dto.THONGKE;
import com.github.lgooddatepicker.components.DatePicker;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author xuand
 */
public class ThongKePanel extends javax.swing.JPanel {
    ThongKeImpl hello = new ThongKeImpl();
    /**
     * Creates new form ThongKePanel
     */
    public ThongKePanel() {
        initComponents();
        // Gọi các phương thức để load dữ liệu vào các bảng
        loadTable();

    }
    public void loadTable(){
        DefaultTableModel model = (DefaultTableModel) DataHoaDonLonNhat.getModel();
        model.setRowCount(0);
        
        DefaultTableModel model2 = (DefaultTableModel) DataBanRa.getModel();
        model2.setRowCount(0);
        
        DefaultTableModel model3 = (DefaultTableModel) DataTrungBinh.getModel();
        model3.setRowCount(0);
        
        ThongKeImpl table = new ThongKeImpl();
        table.DanhSachHoaDon(model);
        table.DanhSachHoaDon(model2);
        table.DanhSachHoaDon(model3);
        
    }
    public void loadChiTieuKhachHang(){
        int makh = Integer.parseInt(MaKhachHang.getText());
        ThongKeImpl hehe = new ThongKeImpl();
        hehe.loadChiTieu(jTextField1, new KHACHANG(makh));   
    }
    public void loadDoanhThuNhanVien(){
        int manv=Integer.parseInt(MaNhanVien.getText());
        ThongKeImpl hehe = new ThongKeImpl();
        hehe.loadDoanhThu(jTextField2, new NHANVIEN(manv));
    }
    public void loadTongDoanhThu(){
        ThongKeImpl hehe = new ThongKeImpl();
        hehe.loadTongTien(sumALL);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ThongKeCuaHang = new javax.swing.JTabbedPane();
        SUM = new javax.swing.JPanel();
        BanRa = new javax.swing.JScrollPane();
        DataBanRa = new javax.swing.JTable();
        BieuDoTuan = new javax.swing.JButton();
        MANV = new javax.swing.JLabel();
        MAKH = new javax.swing.JLabel();
        MaKhachHang = new javax.swing.JTextField();
        sumALLbtn = new javax.swing.JButton();
        sumALL = new javax.swing.JTextField();
        sumKH = new javax.swing.JButton();
        sumNV = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        MaNhanVien = new javax.swing.JTextField();
        MAX = new javax.swing.JPanel();
        HoaDonLonNhat = new javax.swing.JScrollPane();
        DataHoaDonLonNhat = new javax.swing.JTable();
        NgayLapMax = new javax.swing.JPanel();
        ChonNgay1MAX = new javax.swing.JButton();
        ChonNgay2MAX = new javax.swing.JButton();
        nhapngay1MAX = new javax.swing.JTextField();
        nhapngay2MAX = new javax.swing.JTextField();
        TimHoaDonLonNhat = new javax.swing.JButton();
        AVG = new javax.swing.JPanel();
        TrungBinh = new javax.swing.JScrollPane();
        DataTrungBinh = new javax.swing.JTable();
        NgayLapTrungBinh = new javax.swing.JPanel();
        ChonNgay1TB = new javax.swing.JButton();
        ChonNgay2TB = new javax.swing.JButton();
        nhapngay1TB = new javax.swing.JTextField();
        nhapngay2TB = new javax.swing.JTextField();
        KetQuaTB = new javax.swing.JTextField();
        TinhTrungBinh = new javax.swing.JButton();
        BieuDoThang = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        ThongKeCuaHang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thống Kê Cửa Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 12), new java.awt.Color(204, 255, 204))); // NOI18N
        ThongKeCuaHang.setForeground(new java.awt.Color(204, 255, 204));
        ThongKeCuaHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        SUM.setBackground(new java.awt.Color(0, 204, 204));

        DataBanRa.setBackground(new java.awt.Color(204, 255, 204));
        DataBanRa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        DataBanRa.setForeground(new java.awt.Color(0, 51, 51));
        DataBanRa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Mã nhân viên", "Mã khách hàng", "Tên khách hàng", "Ngày lập", "Tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DataBanRa.setShowGrid(true);
        BanRa.setViewportView(DataBanRa);

        BieuDoTuan.setBackground(new java.awt.Color(204, 255, 204));
        BieuDoTuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_futures_30px.png"))); // NOI18N
        BieuDoTuan.setText("Thống kê theo tuần");
        BieuDoTuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BieuDoTuanMouseClicked(evt);
            }
        });
        BieuDoTuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BieuDoTuanActionPerformed(evt);
            }
        });

        MANV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MANV.setText("Mã nhân viên");

        MAKH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MAKH.setText("Mã khách hàng");

        MaKhachHang.setBackground(new java.awt.Color(204, 255, 204));
        MaKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaKhachHangActionPerformed(evt);
            }
        });

        sumALLbtn.setBackground(new java.awt.Color(204, 255, 204));
        sumALLbtn.setForeground(new java.awt.Color(0, 51, 51));
        sumALLbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_us_dollar_30px.png"))); // NOI18N
        sumALLbtn.setText("Tổng");
        sumALLbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sumALLbtnMouseClicked(evt);
            }
        });

        sumALL.setEditable(false);
        sumALL.setBackground(new java.awt.Color(204, 255, 204));
        sumALL.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tổng toàn bộ hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 51, 51))); // NOI18N
        sumALL.setFocusable(false);
        sumALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumALLActionPerformed(evt);
            }
        });

        sumKH.setText("Chi tiêu tổng cộng");
        sumKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sumKHMouseClicked(evt);
            }
        });

        sumNV.setText("Tính tổng doanh thu");
        sumNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sumNVMouseClicked(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setEnabled(false);
        jTextField1.setFocusable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setEnabled(false);
        jTextField2.setFocusable(false);

        MaNhanVien.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout SUMLayout = new javax.swing.GroupLayout(SUM);
        SUM.setLayout(SUMLayout);
        SUMLayout.setHorizontalGroup(
            SUMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SUMLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(SUMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SUMLayout.createSequentialGroup()
                        .addComponent(MANV, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sumNV, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SUMLayout.createSequentialGroup()
                        .addComponent(MAKH, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sumKH, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(SUMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(84, 84, 84)
                .addComponent(sumALL, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sumALLbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BieuDoTuan)
                .addGap(63, 63, 63))
            .addGroup(SUMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BanRa, javax.swing.GroupLayout.DEFAULT_SIZE, 1236, Short.MAX_VALUE)
                .addContainerGap())
        );
        SUMLayout.setVerticalGroup(
            SUMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SUMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SUMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SUMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(sumALL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SUMLayout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(SUMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sumALLbtn)
                                .addComponent(BieuDoTuan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(19, 19, 19)))
                    .addGroup(SUMLayout.createSequentialGroup()
                        .addGroup(SUMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MAKH)
                            .addComponent(sumKH)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SUMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MANV)
                            .addComponent(sumNV)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addComponent(BanRa, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        ThongKeCuaHang.addTab("Tổng giá trị bán ra", SUM);

        MAX.setBackground(new java.awt.Color(0, 204, 204));

        DataHoaDonLonNhat.setAutoCreateRowSorter(true);
        DataHoaDonLonNhat.setBackground(new java.awt.Color(204, 255, 204));
        DataHoaDonLonNhat.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        DataHoaDonLonNhat.setForeground(new java.awt.Color(0, 51, 51));
        DataHoaDonLonNhat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Mã nhân viên", "Mã khách hàng", "Tên khách hàng", "Ngày lập", "Đơn giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DataHoaDonLonNhat.setShowGrid(true);
        HoaDonLonNhat.setViewportView(DataHoaDonLonNhat);

        NgayLapMax.setBackground(new java.awt.Color(0, 204, 204));
        NgayLapMax.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ngày lập", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 51, 51))); // NOI18N

        ChonNgay1MAX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_calendar_31_30px.png"))); // NOI18N
        ChonNgay1MAX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChonNgay1MAXMouseClicked(evt);
            }
        });
        ChonNgay1MAX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChonNgay1MAXActionPerformed(evt);
            }
        });

        ChonNgay2MAX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_calendar_31_30px.png"))); // NOI18N
        ChonNgay2MAX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChonNgay2MAXActionPerformed(evt);
            }
        });

        nhapngay1MAX.setEditable(false);
        nhapngay1MAX.setBackground(new java.awt.Color(204, 255, 204));
        nhapngay1MAX.setForeground(new java.awt.Color(0, 51, 51));
        nhapngay1MAX.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Từ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 51, 51))); // NOI18N

        nhapngay2MAX.setBackground(new java.awt.Color(204, 255, 204));
        nhapngay2MAX.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Đến", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 51, 51))); // NOI18N

        javax.swing.GroupLayout NgayLapMaxLayout = new javax.swing.GroupLayout(NgayLapMax);
        NgayLapMax.setLayout(NgayLapMaxLayout);
        NgayLapMaxLayout.setHorizontalGroup(
            NgayLapMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NgayLapMaxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nhapngay1MAX, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChonNgay1MAX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nhapngay2MAX, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChonNgay2MAX))
        );
        NgayLapMaxLayout.setVerticalGroup(
            NgayLapMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NgayLapMaxLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(NgayLapMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nhapngay1MAX, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(nhapngay2MAX)
                    .addGroup(NgayLapMaxLayout.createSequentialGroup()
                        .addGroup(NgayLapMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChonNgay1MAX)
                            .addComponent(ChonNgay2MAX))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        TimHoaDonLonNhat.setBackground(new java.awt.Color(204, 255, 204));
        TimHoaDonLonNhat.setForeground(new java.awt.Color(0, 51, 51));
        TimHoaDonLonNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-magnifying-glass-30.png"))); // NOI18N
        TimHoaDonLonNhat.setText("Tìm hóa đơn lớn nhất");
        TimHoaDonLonNhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TimHoaDonLonNhatMouseClicked(evt);
            }
        });
        TimHoaDonLonNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimHoaDonLonNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MAXLayout = new javax.swing.GroupLayout(MAX);
        MAX.setLayout(MAXLayout);
        MAXLayout.setHorizontalGroup(
            MAXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MAXLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MAXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MAXLayout.createSequentialGroup()
                        .addComponent(HoaDonLonNhat, javax.swing.GroupLayout.DEFAULT_SIZE, 1236, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(MAXLayout.createSequentialGroup()
                        .addComponent(NgayLapMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TimHoaDonLonNhat)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        MAXLayout.setVerticalGroup(
            MAXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MAXLayout.createSequentialGroup()
                .addGroup(MAXLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NgayLapMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MAXLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TimHoaDonLonNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(HoaDonLonNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );

        ThongKeCuaHang.addTab("Hóa Đơn lớn nhất", MAX);

        AVG.setBackground(new java.awt.Color(0, 204, 204));

        DataTrungBinh.setBackground(new java.awt.Color(204, 255, 204));
        DataTrungBinh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        DataTrungBinh.setForeground(new java.awt.Color(0, 51, 51));
        DataTrungBinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Mã nhân viên", "Mã khách hàng", "Tên khách hàng", "Ngày lập", "Đơn giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DataTrungBinh.setShowGrid(true);
        TrungBinh.setViewportView(DataTrungBinh);

        NgayLapTrungBinh.setBackground(new java.awt.Color(0, 204, 204));
        NgayLapTrungBinh.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ngày lập", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 51, 51))); // NOI18N
        NgayLapTrungBinh.setForeground(new java.awt.Color(0, 51, 51));

        ChonNgay1TB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_calendar_31_30px.png"))); // NOI18N
        ChonNgay1TB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChonNgay1TBActionPerformed(evt);
            }
        });

        ChonNgay2TB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_calendar_31_30px.png"))); // NOI18N
        ChonNgay2TB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChonNgay2TBActionPerformed(evt);
            }
        });

        nhapngay1TB.setBackground(new java.awt.Color(204, 255, 204));
        nhapngay1TB.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Từ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 51, 51))); // NOI18N

        nhapngay2TB.setBackground(new java.awt.Color(204, 255, 204));
        nhapngay2TB.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Đến", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 51, 51))); // NOI18N

        javax.swing.GroupLayout NgayLapTrungBinhLayout = new javax.swing.GroupLayout(NgayLapTrungBinh);
        NgayLapTrungBinh.setLayout(NgayLapTrungBinhLayout);
        NgayLapTrungBinhLayout.setHorizontalGroup(
            NgayLapTrungBinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NgayLapTrungBinhLayout.createSequentialGroup()
                .addComponent(nhapngay1TB, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChonNgay1TB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nhapngay2TB, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChonNgay2TB)
                .addContainerGap())
        );
        NgayLapTrungBinhLayout.setVerticalGroup(
            NgayLapTrungBinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nhapngay1TB, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
            .addComponent(nhapngay2TB)
            .addGroup(NgayLapTrungBinhLayout.createSequentialGroup()
                .addGroup(NgayLapTrungBinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChonNgay1TB)
                    .addComponent(ChonNgay2TB))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        KetQuaTB.setEditable(false);
        KetQuaTB.setBackground(new java.awt.Color(204, 255, 204));
        KetQuaTB.setForeground(new java.awt.Color(0, 51, 51));
        KetQuaTB.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Trung Bình Tất Cả", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 51, 51))); // NOI18N
        KetQuaTB.setFocusable(false);
        KetQuaTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KetQuaTBActionPerformed(evt);
            }
        });

        TinhTrungBinh.setBackground(new java.awt.Color(204, 255, 204));
        TinhTrungBinh.setForeground(new java.awt.Color(0, 51, 51));
        TinhTrungBinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_pie_chart_30px.png"))); // NOI18N
        TinhTrungBinh.setText("Tính Trung Bình");
        TinhTrungBinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TinhTrungBinhMouseClicked(evt);
            }
        });
        TinhTrungBinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TinhTrungBinhActionPerformed(evt);
            }
        });

        BieuDoThang.setBackground(new java.awt.Color(204, 255, 204));
        BieuDoThang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_futures_30px.png"))); // NOI18N
        BieuDoThang.setText("Thống kê theo tháng");
        BieuDoThang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BieuDoThangMouseClicked(evt);
            }
        });
        BieuDoThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BieuDoThangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AVGLayout = new javax.swing.GroupLayout(AVG);
        AVG.setLayout(AVGLayout);
        AVGLayout.setHorizontalGroup(
            AVGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AVGLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AVGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TrungBinh)
                    .addGroup(AVGLayout.createSequentialGroup()
                        .addComponent(NgayLapTrungBinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TinhTrungBinh)
                        .addGap(18, 18, 18)
                        .addComponent(KetQuaTB, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(BieuDoThang)
                        .addGap(0, 230, Short.MAX_VALUE)))
                .addContainerGap())
        );
        AVGLayout.setVerticalGroup(
            AVGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AVGLayout.createSequentialGroup()
                .addGroup(AVGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AVGLayout.createSequentialGroup()
                        .addGroup(AVGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(NgayLapTrungBinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AVGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(KetQuaTB, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(TinhTrungBinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AVGLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BieuDoThang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(TrungBinh, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
        );

        ThongKeCuaHang.addTab("Trung Bình", AVG);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ThongKeCuaHang)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(ThongKeCuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
   
    private void MaKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaKhachHangActionPerformed

    private void ChonNgay1MAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChonNgay1MAXActionPerformed
        // TODO add your handling code here:
        DatePicker datePicker = new DatePicker();
        datePicker.setDateToToday();//đặt mặc định là hôm nay
        datePicker.addDateChangeListener((dce) -> {
            nhapngay1MAX.setText(datePicker.getDateStringOrEmptyString());//set text cho cái textfiled from
        });
    JOptionPane.showMessageDialog(this, datePicker, "Chọn ngày bắt đầu", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_ChonNgay1MAXActionPerformed

    private void TimHoaDonLonNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimHoaDonLonNhatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimHoaDonLonNhatActionPerformed

    private void ChonNgay1TBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChonNgay1TBActionPerformed
        // TODO add your handling code here:
         DatePicker datePicker = new DatePicker();
        datePicker.setDateToToday();//đặt mặc định là hôm nay
        datePicker.addDateChangeListener((dce) -> {
            nhapngay1TB.setText(datePicker.getDateStringOrEmptyString());//set text cho cái textfiled from
        });
    JOptionPane.showMessageDialog(this, datePicker, "Chọn ngày bắt đầu", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_ChonNgay1TBActionPerformed

    private void KetQuaTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KetQuaTBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KetQuaTBActionPerformed

    private void TinhTrungBinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TinhTrungBinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TinhTrungBinhActionPerformed

    private void sumALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumALLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sumALLActionPerformed

    private void ChonNgay2MAXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChonNgay2MAXActionPerformed
        // TODO add your handling code here:
        DatePicker datePicker = new DatePicker();
        datePicker.setDateToToday();//đặt mặc định là hôm nay
        datePicker.addDateChangeListener((dce) -> {
            nhapngay2MAX.setText(datePicker.getDateStringOrEmptyString());//set text cho cái textfiled from
        });
    JOptionPane.showMessageDialog(this, datePicker, "Chọn ngày kết thúc", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_ChonNgay2MAXActionPerformed

    private void ChonNgay2TBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChonNgay2TBActionPerformed
        // TODO add your handling code here:
         DatePicker datePicker = new DatePicker();
        datePicker.setDateToToday();//đặt mặc định là hôm nay
        datePicker.addDateChangeListener((dce) -> {
            nhapngay2TB.setText(datePicker.getDateStringOrEmptyString());//set text cho cái textfiled from
        });
    JOptionPane.showMessageDialog(this, datePicker, "Chọn ngày kết thúc", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_ChonNgay2TBActionPerformed

    private void BieuDoTuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BieuDoTuanMouseClicked
        // TODO add your handling code here:
        Bus.Impl.ThongKeImpl.drawcharttheotuan();
    }//GEN-LAST:event_BieuDoTuanMouseClicked

    private void BieuDoTuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BieuDoTuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BieuDoTuanActionPerformed

    private void BieuDoThangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BieuDoThangMouseClicked
        // TODO add your handling code here:
        Bus.Impl.ThongKeImpl.drawcharttheothang();
    }//GEN-LAST:event_BieuDoThangMouseClicked

    private void ChonNgay1MAXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChonNgay1MAXMouseClicked

    }//GEN-LAST:event_ChonNgay1MAXMouseClicked

    private void BieuDoThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BieuDoThangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BieuDoThangActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void sumKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumKHMouseClicked
        // TODO add your handling code here:
        loadChiTieuKhachHang();
    }//GEN-LAST:event_sumKHMouseClicked

    private void sumNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumNVMouseClicked
        // TODO add your handling code here:
        loadDoanhThuNhanVien();
    }//GEN-LAST:event_sumNVMouseClicked

    private void sumALLbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumALLbtnMouseClicked
        // TODO add your handling code here:
        loadTongDoanhThu();
    }//GEN-LAST:event_sumALLbtnMouseClicked

    private void TimHoaDonLonNhatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TimHoaDonLonNhatMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) DataHoaDonLonNhat.getModel();
        model.setRowCount(0);
        String n1 = nhapngay1MAX.getText();
        String n2 = nhapngay2MAX.getText();
        hello.loadHoaDonMax(model,n1,n2);
        
    }//GEN-LAST:event_TimHoaDonLonNhatMouseClicked

    private void TinhTrungBinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TinhTrungBinhMouseClicked
        // TODO add your handling code here:
        String n1=nhapngay1TB.getText();
        String n2=nhapngay2TB.getText();
        hello.loadHoaDonTB(KetQuaTB, n1, n2);
    }//GEN-LAST:event_TinhTrungBinhMouseClicked
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AVG;
    private javax.swing.JScrollPane BanRa;
    private javax.swing.JButton BieuDoThang;
    private javax.swing.JButton BieuDoTuan;
    private javax.swing.JButton ChonNgay1MAX;
    private javax.swing.JButton ChonNgay1TB;
    private javax.swing.JButton ChonNgay2MAX;
    private javax.swing.JButton ChonNgay2TB;
    private javax.swing.JTable DataBanRa;
    private javax.swing.JTable DataHoaDonLonNhat;
    private javax.swing.JTable DataTrungBinh;
    private javax.swing.JScrollPane HoaDonLonNhat;
    private javax.swing.JTextField KetQuaTB;
    private javax.swing.JLabel MAKH;
    private javax.swing.JLabel MANV;
    private javax.swing.JPanel MAX;
    private javax.swing.JTextField MaKhachHang;
    private javax.swing.JTextField MaNhanVien;
    private javax.swing.JPanel NgayLapMax;
    private javax.swing.JPanel NgayLapTrungBinh;
    private javax.swing.JPanel SUM;
    private javax.swing.JTabbedPane ThongKeCuaHang;
    private javax.swing.JButton TimHoaDonLonNhat;
    private javax.swing.JButton TinhTrungBinh;
    private javax.swing.JScrollPane TrungBinh;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField nhapngay1MAX;
    private javax.swing.JTextField nhapngay1TB;
    private javax.swing.JTextField nhapngay2MAX;
    private javax.swing.JTextField nhapngay2TB;
    private javax.swing.JTextField sumALL;
    private javax.swing.JButton sumALLbtn;
    private javax.swing.JButton sumKH;
    private javax.swing.JButton sumNV;
    // End of variables declaration//GEN-END:variables
}
